runtime: php
env: flex

runtime_config: 
   operating_system: "ubuntu22"
   document_root: public

# Ensure we skip ".env", which is only for local development
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:0z+UyOvIVqB9J+Dx4QVdvPNIX7DsJjpoeS0A+2tb89Y=
    APP_NAME: "GCP App - CODE"

    LOG_LEVEL: debug

build_env_variables:
    GOOGLE_COMPOSER_VERSION: 2.2.1